- name: "Get go-asdf location"
  command: "~/.asdf/bin/asdf which go"
  register: go_location
  check_mode: no
  changed_when: false
  tags: golang


- name: "install Go Packages"
  command: "{{ go_location.stdout }} get {{ item }}"
  with_items: "{{ default_packages }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/Code/go"
  changed_when: false
  tags: golang

- name: "Symlink it to bazel trucker!"
  file:
    src: "{{ ansible_env.HOME }}/Code/go/bin/bazelisk"
    dest: "{{ ansible_env.HOME }}/.local/bin/bazel"
    state: link
  tags:
    - golang
    - bazelisk
