---
- name: emacs install
  community.general.pacman:
    name: emacs
  become: true
- name: vim install
  community.general.pacman:
    name: vim
  become: true

- kewlfft.aur.aur:
    name: visual-studio-code-bin
  become: true
  become_user: aur_builder
