
- name: emacs install
  community.general.pacman:
    name: emacs
  become: True

- name: vim install
  community.general.pacman:
    name: vim
  become: True

- aur:
    name: visual-studio-code-bin
  become: True
  become_user: aur_builder
