- include_tasks: "main_arch.yml"
  when: ansible_distribution == "Archlinux"

- include_tasks: "main_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- include_tasks:
    file: main_mac.yml
  when: ansible_distribution == 'MacOSX'

- name: "emacs doom git repository"
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
  register: emacs_doom

- name: "Stat doom folder"
  stat:
    path: ~/.doom.d
  register: doom_path

- name: "Install doom if folder not exists"
  command: ~/.emacs.d/bin/doom --yes install
  when: not doom_path.stat.exists
