- include_tasks: "main_arch.yml"
  when: ansible_distribution == "Archlinux"

- include_tasks: "main_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- include_tasks:
    file: main_mac.yml
    apply:
      tags: editor
  when: ansible_distribution == 'MacOSX'
  tags: editor

- include_tasks:
    file: main_systemd.yml
    apply:
      tags: editor
  tags: editor
  when: ansible_distribution != "MacOSX"

- name: "emacs doom git repository"
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
  register: emacs_doom
  tags: editor

- name: "Stat doom folder"
  stat:
    path: ~/.doom.d
  register: doom_path
  tags: editor

- name: "Install doom if folder not exists"
  command: ~/.emacs.d/bin/doom --yes install
  when: not doom_path.stat.exists
  tags: editor

- name: Make sure ssh-agent is enabled
  systemd:
    name: emacs-daemon
    scope: user
    enabled: true
  when: ansible_distribution != "MacOSX"
  tags: editor
