---
- name: Run package upgrades
  hosts: base
  roles:
    - command
    - browsers

- name: Run package upgrades
  hosts: linux
  roles:
    - snap
    - lib_dependencies
    - yubikey
    - bluetooth
    - 1password
    - planner
