---
- name: Run package upgrades
  hosts: base
  roles:
    - command
    - browsers    
    - 1password
    - ollama


- name: Run package upgrades
  hosts: linux
  roles:
    - lib_dependencies
    - yubikey
    - bluetooth
