---
- name: Run Base
  hosts: base
  roles:
    - base_packages

- name: Run Linux base
  hosts: linux
  roles:
    - aur
    - ssh
    - kernel_settings
    - linux-fonts

- name: "Run Mac Base"
  hosts: mac
  roles:    
    - mac-fonts
