- name: "base roles"
  hosts: base
  roles:
    - fishshell
    - starship
    - chat_applications

- name: linux roles
  hosts: linux
  roles:
    - sway
    - pipewire
    - kitty
    - light
    - wl-clipboard
    - wf_recorder
    - kanshi
    - albert
    - ags

- name:
  hosts: mac
  roles:
    - karabiner
