-
- name: "Install pulseaudio and other good stuff"
  community.general.pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - gstreamer
      - libldac
      - playerctl
  become: True
  tags: pulseaudio

- kewlfft.aur.aur:
    name:
      - pacmixer
  become: True
  become_user: aur_builder
  tags: pulseaudio
