- name: "Get Kanshi"
  apt:
    name:
    - kanshi
  become: True
  when: ansible_distribution == "Ubuntu"


- community.general.pacman:
    name: kanshi
  become: True
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"
