- name: "Get Kanshi"
  apt:
    name:
    - kanshi
  become: True
  when: ansible_distribution == "Ubuntu"


- kewlfft.aur.aur:
    name: kanshi-git
  become: True
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"
