- include_tasks: main_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: main_arch.yml
  when: ansible_distribution == "Archlinux"

- name: "Ensure other deps are made available"
  pip:
    executable: pip3
    name:
      - pipenv
      - psutil
      - emoji
      - pulsectl
      - cookiecutter
      - ninja
      - meson
      - pre-commit
    state: latest
  tags:
    - python
