- include_tasks: main_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: main_arch.yml
  when: ansible_distribution == "Archlinux"

- community.general.homebrew:
    name:
      - python3
  when: ansible_distribution == "MacOSX"

- name: "Ensure linux Python deps are made available"
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  with_items:
  - ninja
  - meson
  tags:
    - python
  when: ansible_distribution == "Archlinux" or ansible_distribution == "Ubuntu"

- name: "Ensure other deps are made available"
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  with_items:
  - pipenv
  - cookiecutter
  - pre-commit
  - sqlfluff
  - gpt-command-line
  tags:
    - python
