- include_tasks: main_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: main_arch.yml
  when: ansible_distribution == "Archlinux"

- community.general.homebrew:
    name:
      - python3
      - python-packaging
      - pipx
  when: ansible_distribution == "MacOSX"

- name: "Register where pipx is installed"
  command: "which pipx"
  register: pipx_location
  check_mode: no
  changed_when: False

- name: "Ensure linux Python deps are made available"
  community.general.pipx:
    name: "{{ item }}"
    state: latest
    executable: "{{ pipx_location.stdout }}"
  with_items:
  - ninja
  - meson
  tags:
    - python
  when: ansible_distribution == "Archlinux" or ansible_distribution == "Ubuntu"

- name: "Ensure other deps are made available"
  community.general.pipx:
    name: "{{ item }}"
    state: latest
    executable: "{{ pipx_location.stdout }}"
  with_items:
  - pipenv
  - cookiecutter
  - pre-commit
  - sqlfluff
  - gpt-command-line
  tags:
    - python
