- user:
    name: aur_builder
    group: wheel
  become: True
  when: ansible_distribution == "Ubuntu"

- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: True
  when: ansible_distribution == "Ubuntu"

- name: "Ensure aur_builder .gnupg folder exists"
  file:
    path: "/home/aur_builder/.gnupg"
    state: directory
  become: True
  become_user: aur_builder
  when: ansible_distribution == "Ubuntu"

- name: "Copy our dirmngr.conf"
  copy:
    src: files/dirmngr.conf
    dest: /home/aur_builder/.gnupg/dirmngr.conf
  notify: kill-aur-builder-dirmngr
  become: True
  become_user: aur_builder
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers

- name: "Get existing keys"
  shell: gpg --with-colons --fingerprint | awk "-F:" '$1 == "fpr" {print $10;}'
  become: True
  become_user: aur_builder
  register: gpg_keys
  changed_when: False
  when: ansible_distribution == "Ubuntu"

- name: "Import specific keys that are nice :tm:"
  command: "gpg --keyserver {{ item.keyserver }} --recv-keys {{ item.key }}"
  become: True
  become_user: aur_builder
  when: item.key not in gpg_keys.stdout_lines
  with_items: "{{ keys }}"
  when: ansible_distribution == "Ubuntu"

- name: Upgrade all packages...
  kewlfft.aur.aur:
    upgrade: True
  become: True
  become_user: aur_builder
  when: ansible_distribution == "Ubuntu"
