- community.general.homebrew:
    name:
      - asdf

- name: "Create completions folder"
  file:
    path: ~/.config/fish/completions
    state: directory

- name: "Install asdf plugins"
  tags:
    - asdf
  command: "asdf plugin add {{ item.name }} {{ item.repo | default('')}}"
  with_items: "{{ asdf_packages }}"
  register: asdf_plugin
  failed_when: "asdf_plugin.rc not in (0, 2)"
  changed_when: "asdf_plugin.rc != 2"

- name: "Run asdf plugin hooks"
  tags:
    - asdf
  command: "{{ item.hook}}"
  with_items: "{{ asdf_packages }}"
  when: item.hook is defined
  register: asdf_hook
  failed_when: "asdf_hook.rc not in (0, 2)"
  changed_when: false

- name: "Set package versions"
  tags:
    - asdf
  command: "asdf set {{ item.name }} {{ item.version | default('latest') }}"
  with_items: "{{ asdf_packages }}"
  changed_when: false

- name: "Install asdf packages"
  tags:
    - asdf
  command: "asdf install {{ item.name }} {{ item.version | default('latest') }}"
  with_items: "{{ asdf_packages }}"
  register: async_asdf_package
  async: 60
  poll: 0
  changed_when: false

- name: Wait for all asdf packages to have been installed
  tags:
    - asdf
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: _asdf_install_result
  retries: 20
  delay: 2
  until: _asdf_install_result.finished
  loop: "{{ async_asdf_package.results }}"
  changed_when: _asdf_install_result.finished and _asdf_install_result.stdout is not search("already installed")

- name: "Set global versions"
  tags:
    - asdf
  command: "asdf global {{ item.name }} {{ item.version | default('latest') }}"
  with_items: "{{ asdf_packages }}"
  changed_when: false

- name: "Force reshim after plugins"
  tags:
    - asdf
  command: "asdf reshim"
  changed_when: false
