---
- name: "Install font dependencies"
  apt:
    name:
      - fontconfig
      - fonts-noto-color-emoji
      - fonts-powerline
      - fonts-roboto
      - fonts-font-awesome
  become: true
  when: ansible_distribution == "Ubuntu"

- name: "Install font dependencies"
  community.general.pacman:
    name:
      - fontconfig
      - ttf-font-awesome
      - ttf-roboto
      - noto-fonts-emoji
      - adobe-source-han-sans-otc-fonts
      - adobe-source-han-sans-otc-fonts
  become: True
  when: ansible_distribution == "Archlinux"

- kewlfft.aur.aur:
    name: powerline-fonts-git
  become: True
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"
