- include_tasks: main_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: main_arch.yml
  when: ansible_distribution == "Archlinux"


- name: "Add acpid brightness controls"
  copy:
    src: "files/{{ item }}"
    dest: "/etc/{{ item }}"
  with_items:
    - acpi/events/bl-down
    - acpi/events/bl-up
  become: True
  tags:
    - light
