- import_tasks: main_ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - light

- import_tasks: main_arch.yml
  when: ansible_distribution == "Archlinux"
  tags:
    - light

#- name: ensure folder
#  ansible.builtin.file:
#    path: /etc/acpi/events
#    state: directory
#  become: True
#  tags:
#    - light

- name: "Add acpid brightness controls"
  copy:
    src: "files/{{ item }}"
    dest: "/etc/{{ item }}"
  with_items:
    - acpi/events/bl-down
    - acpi/events/bl-up
  become: True
  tags:
    - light
