- name: "Tools"
  community.general.pacman:
    name:
      - neofetch
      - ranger
      - curl
      - unzip
      - wget
      - fzf
      - htop
      - x11-ssh-askpass
      - jq
      - the_silver_searcher
      - ncdu
      - ripgrep
      - xdg-utils
      - atool
      - tree
      - cloc
      - mercurial
      - ansible-lint
      - remmina
      - freerdp
  become: true

- name: "Install virtualbox"
  community.general.pacman:
    name:
      - virtualbox
      - virtualbox-host-dkms
  become: True

- name: Tools from AUR
  aur:
    name:
      - spotify
      - gcalcli
      - spicetify-cli
      - spicetify-themes-git
  become: True
  become_user: aur_builder

- name: AWS Tools from AUR
  aur:
    name:
      - aws-cli-v2-bin
      - aws-session-manager-plugin
  become: True
  become_user: aur_builder
