- include_tasks:
    file: main_ubuntu.yml
    apply:
      tags: tools
  when: ansible_distribution == "Ubuntu"
  tags: tools

- include_tasks:
    file: main_arch.yml
    apply:
      tags: tools
  when: ansible_distribution == "Archlinux"
  tags: tools

- include_tasks:
    file: main_mac.yml
    apply:
      tags: tools
  when: ansible_distribution == 'MacOSX'
  tags: tools