- name: "Ensure neofetch is available"
  apt:
    name:
      - neofetch
      - ranger
  become: true

- name: "Install utilities"
  apt:
    name:
      - curl
      - unzip
      - wget
      - fzf
      - htop
      - net-tools
      - wl-clipboard
      - ssh-askpass
      - jq
      - silversearcher-ag
      - ncdu
      - ripgrep
      - xdg-utils
      - mime-support
      - atool
      - tree
      - cloc
      - mercurial
  become: true

- name: "Install Snap stuff"
  snap:
    name: spotify
  become: true