- name: "Tools"
  community.general.pacman:
    name:
      - neofetch
      - ranger
      - curl
      - unzip
      - wget
      - fzf
      - htop
      - x11-ssh-askpass
      - jq
      - the_silver_searcher
      - ncdu
      - ripgrep
      - xdg-utils
      - atool
      - tree
      - cloc
      - mercurial
      - ansible-lint
      - remmina
      - freerdp
      - bind
      - git-absorb
      - cameractrls
  become: true

- name: "Install virtualbox"
  community.general.pacman:
    name:
      - virtualbox
      - virtualbox-host-dkms
  become: True

- name: "Music"
  community.general.pacman:
    name:
      - spotify-launcher
  become: true
