
- name: "Create docker group"
  group:
    name: docker
  become: True
  tags: docker

- name: "Add current user to docker group"
  user:
    name: "{{ ansible_env.USER }}"
    group: docker
  become: True
  tags: docker
