- name: Install basic sway and its dependencies
  apt:
    name:
      - swaybg
      - swayidle
      - slurp
      - grim
      - ffmpeg
      - brightnessctl
      - libpango-1.0-0
      - acpid
      - playerctl
      - gir1.2-playerctl-2.0
      - sway
      - waybar
      - swaylock
  become: True
  tags:
    - sway

- name: "Install dependency"
  apt:
    name:
      - libxml2-dev
      - graphviz
      - doxygen
      - xmlto
  become: True
  tags:
    - sway

- name: "Copy misc file"
  copy:
    src: "{{ waybar_path | expanduser }}/resources/custom_modules/mediaplayer.py"
    dest: "/usr/local/bin/mediaplayer.py"
    remote_src: yes
    mode: preserve
  become: True
  tags:
    - waybar

- name: "Clone swaylock"
  git:
    repo: "https://github.com/swaywm/swaylock"
    dest: "{{swaylock_path}}"
  tags:
    - wayland
  notify:
    - swaylock-changed

- name: "Clone swayidle"
  git:
    repo: "https://github.com/swaywm/swayidle"
    dest: "{{swayidle_path}}"
  tags:
    - wayland
  notify:
    - swayidle-changed

- meta: flush_handlers
