- name: Install basic sway and its dependencies
  apt:
    name:
      - swaybg
      - swayidle
      - slurp
      - grim
      - ffmpeg
      - brightnessctl
      - libpango-1.0-0
      - acpid
      - playerctl
      - gir1.2-playerctl-2.0
      - sway
      - waybar
      - swaylock
      - xwayland
      - wofi
  become: True
  tags:
    - sway

- name: "Install dependency"
  apt:
    name:
      - libxml2-dev
      - graphviz
      - doxygen
      - xmlto
  become: True
  tags:
    - sway
