- community.general.pacman:
    name:
      - starship
  become: True
  when: ansible_distribution == "Archlinux"

- community.general.homebrew:
    name:
      - starship
  when: ansible_distribution == "MacOSX"

- name: Install starship
  community.general.snap:
    name:
      - starship
    channel: edge
  become: True
  when: ansible_distribution == "Ubuntu"
