- include_tasks: "main_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- include_tasks: "main_arch.yml"
  when: ansible_distribution == "Archlinux"

- community.general.homebrew_cask:
    name:
      - google-cloud-sdk
  when: ansible_distribution == "MacOSX"
