
- name: "Ensure cache is updated"
  kewlfft.aur.aur:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - libpipewire02
  tags:
    - pipewire
  become_user: aur_builder
  become: True

- name: make sure xdg-desktop-portal is running
  systemd:
    name: xdg-desktop-portal
    enabled: yes
    scope: user
  tags:
    - pipewire

- name: make sure pipewire and its components are running
  systemd:
    name: "{{item}}"
    enabled: yes
    scope: user
  with_items:
    - pipewire
    - pipewire-pulse
  tags:
    - pipewire
