
- name: "Ensure cache is updated"
  kewlfft.aur.aur:
    name:
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
  tags:
    - pipewire
  become_user: aur_builder
  become: True
  when: ansible_distribution == "Archlinux"

- community.general.pacman:
    name:
      - pipewire
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
  tags:
    - pipewire
  become: True
  when: ansible_distribution == "Archlinux"

- name: make sure pipewire and its components are running
  systemd:
    name: "{{item}}"
    enabled: yes
    scope: user
  with_items:
    - pipewire
    - pipewire-pulse
  tags:
    - pipewire
  when: ansible_distribution == "Archlinux"

- name: install pipewire and deps
  apt:
    name: 
      - libldacbt-abr2
      - libldacbt-enc2
      - libspa-0.2-bluetooth
      - pipewire-audio-client-libraries
      - wireplumber
  become: True
  when: ansible_distribution == "Ubuntu"

- name: ensure pulseaudio is removed
  apt:
    name: 
      - pulseaudio-module-bluetooth
      - pipewire-media-session
    state: absent
  become: True
  when: ansible_distribution == "Ubuntu"

- name: make sure pipewire and its components are running
  systemd:
    name: "{{item}}"
    enabled: yes
    scope: user
  with_items:
    - wireplumber.service
  tags:
    - pipewire
  when: ansible_distribution == "Ubuntu"


