- name: Add an Apt signing key to a specific keyring file
  apt_key:
    url: https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_23.10/Release.key
  become: True

- name: "Add albert package source"
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_23.10/ /"
    state: present
  become: True
  register: albert_package_source

- name: Update cache if we just added the above
  apt:
    update_cache: true
  when: "albert_package_source.changed|bool"
  become: True

- name: Install albert
  apt:
    name:
      - albert
  become: true
