- kewlfft.aur.aur:
    name:
      - discord
      - slack-desktop
  become: True
  become_user: aur_builder
  tags:
    - chat_applications
  when: ansible_distribution == "Archlinux"

- community.general.pacman:
    name:
      - discord
  become: True
  tags:
    - chat_applications
  when: ansible_distribution == "Archlinux"

- community.general.homebrew_cask:
    name:
      - discord
      - whatsapp
      - slack
      - signal
  tags:
    - chat_applications
  when: ansible_distribution == "MacOSX"

- name: "Install Snap stuff"
  snap:
    name: 
      - discord
      - whatsdesk
  tags:
    - chat_applications
  when: ansible_distribution == "Ubuntu"
  become: true
