- name: "Install ly"
  kewlfft.aur.aur:
    name:
      - ly-git
  become: True
  become_user: aur_builder

- name: "Enable ly.service"
  systemd:
    enabled: yes
    name: ly
  become: True

- name: "Set config file"
  template:
    src: "files/config.ini"
    dest: "/etc/ly/config.ini"
    owner: root
    group: root
    mode: '0644'
  become: True
