- name: Install rbenv and ruby-build
  become: "{{ ansible_system == 'Linux' }}"
  ansible.builtin.package:
    name:
      - rbenv
      - ruby-build
    state: present

- name: Install ruby
  ansible.builtin.command:
    cmd: "rbenv install {{ ruby_version }} --skip-existing"
  changed_when: false

- name: Set global ruby version
  ansible.builtin.command:
    cmd: "rbenv global {{ ruby_version }}"
  changed_when: false

- name: Install bundler
  ansible.builtin.shell: "rbenv init - --no-rehash bash | source && gem install bundler"
  args:
    executable: /bin/bash
  changed_when: false
